name: Debug Build
on:
  pull_request:
  push:
    branches:
      - main
      - develop
# Where will they run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build org.tiqr.authenticator APK
      run: bash ./gradlew assembleProductionRelease --stacktrace
    - name: Build org.tiqr.authenticator.testing APK
      run: bash ./gradlew assembleAcceptanceRelease --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app-production-release-unsigned
        path: app/build/outputs/apk/production/release/app-production-release-unsigned.apk
    - name: Upload testing APK
      uses: actions/upload-artifact@v1
      with:
        name: app-acceptance-release-unsigned
        path: app/build/outputs/apk/acceptance/release/app-acceptance-release-unsigned.apk
